In [59]:
import pandas as pd

df = pd.read_csv("data/superstore_cleaned.csv", index_col = "Row ID")

#Re-apply dtypes
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])
df["Postal Code"] = df["Postal Code"].astype(str)

df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [60]:
#Making a new column for year, month, and month no
df["Order Date Year"] = df["Order Date"].dt.year
df["Order Date Month"] = df["Order Date"].dt.strftime("%b")
df["Order Date Month No"] = df["Order Date"].dt.month
df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Order Date Year,Order Date Month,Order Date Month No
Row ID,,,,,,,,,,,,,,,,,,,,
1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2017,Nov,11
2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017,Nov,11
3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017,Jun,6
4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016,Oct,10
5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2016,Oct,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9796,CA-2017-125920,2017-05-21,2017-05-28,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980,2017,May,5
9797,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680,2016,Jan,1
9798,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880,2016,Jan,1
9799,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760,2016,Jan,1
9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840,2016,Jan,1

In [61]:
df.describe()

,Order Date,Ship Date,Sales,Order Date Year,Order Date Month No
count,9788,9788,9788.000000,9788.000000,9788.000000
mean,2017-05-01 04:40:42.174090,2017-05-05 03:44:47.862689,230.110956,2016.723743,7.823049
min,2015-01-03 00:00:00,2015-01-07 00:00:00,0.444000,2015.000000,1.000000
25%,2016-05-23 00:00:00,2016-05-27 00:00:00,17.248000,2016.000000,5.000000
50%,2017-06-26 00:00:00,2017-06-29 00:00:00,54.376000,2017.000000,9.000000
75%,2018-05-15 06:00:00,2018-05-19 06:00:00,210.104000,2018.000000,11.000000
max,2018-12-30 00:00:00,2019-01-05 00:00:00,22638.480000,2018.000000,12.000000
std,NaN,NaN,625.333809,1.124106,3.277804

In [62]:
#Sorting the month using "Order Date Month No" column, then grouping it by year using for loop

df = df.sort_values("Order Date Month No")

years = [2015, 2016, 2017, 2018]
dfs = {}

for year in years:
    dfs[year] = df[df["Order Date Year"] == year].copy()

df

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Order Date Year,Order Date Month,Order Date Month No
Row ID,,,,,,,,,,,,,,,,,,,,
9800,CA-2016-128608,2016-01-12,2016-01-17,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384,2016,Jan,1
7476,CA-2015-167199,2015-01-06,2015-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,Kentucky,42420.0,South,OFF-BI-10004632,Office Supplies,Binders,Ibico Hi-Tech Manual Binding System,609.980,2015,Jan,1
7475,CA-2015-167199,2015-01-06,2015-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,2015,Jan,1
5030,CA-2018-139304,2018-01-29,2018-02-02,Standard Class,VG-21790,Vivek Gonzalez,Consumer,United States,San Francisco,California,94109.0,West,OFF-AR-10001216,Office Supplies,Art,Newell 339,8.340,2018,Jan,1
2376,CA-2018-119669,2018-01-24,2018-01-30,Standard Class,TP-21130,Theone Pippenger,Consumer,United States,Smyrna,Georgia,30080.0,South,OFF-FA-10000053,Office Supplies,Fasteners,Revere Boxed Rubber Bands by Revere,5.670,2018,Jan,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4226,US-2015-102631,2015-12-13,2015-12-17,Standard Class,EB-13840,Ellis Ballard,Corporate,United States,Chicago,Illinois,60623.0,Central,FUR-FU-10003930,Furniture,Furnishings,Howard Miller 12-3/4 Diameter Accuwave DS Wal...,94.428,2015,Dec,12
4240,CA-2018-158673,2018-12-29,2019-01-04,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Grand Rapids,Michigan,49505.0,Central,OFF-PA-10000994,Office Supplies,Paper,Xerox 1915,209.700,2018,Dec,12
4249,CA-2017-157336,2017-12-01,2017-12-05,Second Class,SJ-20500,Shirley Jackson,Consumer,United States,Fairfield,Connecticut,6824.0,East,OFF-BI-10004236,Office Supplies,Binders,"XtraLife ClearVue Slant-D Ring Binder, White, 3""",88.080,2017,Dec,12
8391,CA-2018-153227,2018-12-04,2018-12-06,First Class,CS-12250,Chris Selesnick,Corporate,United States,Los Angeles,California,90032.0,West,OFF-PA-10001838,Office Supplies,Paper,Adams Telephone Message Book W/Dividers/Space ...,11.760,2018,Dec,12
4896,CA-2017-135776,2017-12-23,2017-12-30,Standard Class,EH-13765,Edward Hooks,Corporate,United States,Seattle,Washington,98103.0,West,OFF-EN-10004773,Office Supplies,Envelopes,Staple envelope,61.960,2017,Dec,12

In [63]:
df["Ship Mode"].value_counts()

Ship Mode
Standard Class    5848
Second Class      1901
First Class       1501
Same Day           538
Name: count, dtype: int64

In [64]:
df["Segment"].value_counts()

Segment
Consumer       5096
Corporate      2948
Home Office    1744
Name: count, dtype: int64

In [65]:
df["Category"].value_counts()

Category
Office Supplies    5903
Furniture          2075
Technology         1810
Name: count, dtype: int64

In [66]:
#Median of Sales by Year 

df_year_sales = df.pivot_table(
    index = ["Order Date Month No", "Order Date Month"],
    columns = "Order Date Year",
    values = "Sales",
    aggfunc = "median"
).sort_index().droplevel("Order Date Month No")


df_year_sales

Order Date Year     2015    2016    2017    2018
Order Date Month
Jan               38.600  62.982  60.055  40.300
Feb               23.968  41.252  89.970  62.777
Mar               47.946  44.935  76.920  61.000
Apr               55.480  59.520  41.568  39.620
May               56.400  51.560  45.576  49.230
Jun               62.016  43.056  47.760  64.140
Jul               44.010  82.485  48.278  60.830
Aug               49.204  49.840  44.784  73.286
Sep               49.980  60.672  46.530  47.520
Oct               55.984  57.732  53.736  46.660
Nov               53.080  68.160  52.692  58.569
Dec               56.544  58.080  65.820  49.828

In [67]:
#Total sales by Category from 2015 to 2018 

df_cat_year = df.pivot_table(
    index = "Order Date Year",
    columns = "Category",
    values = "Sales",
    aggfunc = "sum"
)

df_cat_year

Category           Furniture  Office Supplies  Technology
Order Date Year
2015             156196.5091       149512.820  173865.507
2016             158933.7674       133124.407  162257.731
2017             195813.0400       180845.236  220567.214
2018             212313.7872       239730.361  269165.661

In [68]:
#Top 10 Most Selling Sub-Category by year 
years = [2015, 2016, 2017, 2018]
df_subcat = {}

for year in years:
    df_subcat[year] = dfs[year].groupby("Sub-Category")["Sales"].sum().sort_values(ascending = False).head(10)

#testing the loop
df_subcat[2015]

Sub-Category
Phones         77225.9560
Chairs         76765.0680
Machines       62023.3730
Storage        49197.5260
Tables         45757.7775
Binders        43263.2670
Accessories    23766.3960
Bookcases      20036.6776
Appliances     15160.7150
Supplies       14335.6200
Name: Sales, dtype: float64

In [69]:
#Sales by Ship mode per segment
df_shipmode_segment = df.pivot_table(
    index = "Ship Mode",
    columns = "Segment",
    values = "Sales",
    aggfunc = "median"
)

df_shipmode_segment

Segment         Consumer  Corporate  Home Office
Ship Mode
First Class       53.568     54.648       59.955
Same Day          47.396     83.565       58.364
Second Class      52.860     54.896       71.928
Standard Class    55.200     55.440       45.670

In [70]:
#Top 5 states with most orders by region 

df_east = df[df["Region"] == "East"].groupby("State").size().sort_values(ascending = False).head()
df_west = df[df["Region"] == "West"].groupby("State").size().sort_values(ascending = False).head()
df_central = df[df["Region"] == "Central"].groupby("State").size().sort_values(ascending = False).head()
df_south = df[df["Region"] == "South"].groupby("State").size().sort_values(ascending = False).head()

In [71]:
#Sales by Segment from 2015 - 2018

years = [2015, 2016, 2017, 2018]
df_sales_segment = {}

for year in years:
    df_sales_segment[year] = dfs[year].groupby("Segment")["Sales"].sum()

#testing the loop
df_sales_segment[2015]

Segment
Consumer       262956.8006
Corporate      127797.4957
Home Office     88820.5398
Name: Sales, dtype: float64